name = "IMASdd"
uuid = "c5a45a97-b3f9-491c-b9a7-aa88c3bc0067"
version = "8.2.3"
authors = ["Orso Meneghini <orso82@gmail.com>"]

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
AdaptiveArrayPools = "4f381ef7-9af0-4cbe-99d4-cf36d7b0f233"
CoordinateConventions = "7204ce3a-f536-43d2-be4a-fbed74e90d86"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Memoization = "6fafb56a-5788-4b4e-91ca-c0cea6611c73"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"
ThreadSafeDicts = "4239201d-c60e-5e0a-9702-85d713665ba7"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
AbstractTrees = "0.4"
AdaptiveArrayPools = "0.1"
CoordinateConventions = "1"
DataInterpolations = "7, 8"
Dates = "1.11.0"
HDF5 = "0.17"
JSON = "0.21"
Memoization = "0.2.2"
OrderedCollections = "1"
PrecompileTools = "1"
StaticArraysCore = "1"
ThreadSafeDicts = "0.1.6"
TimerOutputs = "0.5"
julia = "1"
